# Generated by Django 5.2.17 on 2026-09-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Kargu/jabatan, mis. Peskizador Senior",
                        max_length=150,
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="staff/")),
                ("bio", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Utilizador",
                "verbose_name_plural": "Perfil Utilizador",
            },
        ),
    ]
