# Generated by Django 6.1.1 on 2026-09-11 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairmanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Estevanus Coli', max_length=150)),
                ('role', models.CharField(default='Diretor Ezekutivu, Mata Dalan Institute', max_length=150)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/team/')),
            ],
            options={
                'verbose_name': 'Mensajen Diretor',
                'verbose_name_plural': 'Mensajen Diretor',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensajen Kontaktu',
                'verbose_name_plural': 'Mensajen Kontaktu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/partners/')),
                ('type', models.CharField(choices=[('partner', 'Parseiru'), ('donor', 'Doador')], default='partner', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parseiru / Doador',
                'verbose_name_plural': 'Parseiru / Doador',
                'ordering': ['type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-diagram-3', help_text='Nome klase ikon Bootstrap Icons', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programa',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(help_text='Teks kecil di atas judul', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='website/slides/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide Hero',
                'verbose_name_plural': 'Slide Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Vizaun & Misaun',
                'verbose_name_plural': 'Vizaun & Misaun',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_title', models.CharField(default='Profile', max_length=150)),
                ('profile_text', models.TextField()),
                ('who_we_are_text', models.TextField()),
                ('established_year', models.CharField(default='2000', max_length=10)),
                ('based_in', models.CharField(default='Bebonuk, Comoro, Dili, Timor-Leste', max_length=150)),
                ('focus_area', models.CharField(default='Monitoring, Advocacy & Community Strengthening', max_length=200)),
            ],
            options={
                'verbose_name': 'Ita Se (Who We Are)',
                'verbose_name_plural': 'Ita Se (Who We Are)',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/activities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Custom.municipality')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividade',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'context': 'article'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Custom.category')),
            ],
            options={
                'verbose_name': 'Artigu',
                'verbose_name_plural': 'Artigu',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='website/documents/')),
                ('published_date', models.DateField()),
                ('category', models.ForeignKey(limit_choices_to={'context': 'document'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Custom.category')),
            ],
            options={
                'verbose_name': 'Dokumentu',
                'verbose_name_plural': 'Dokumentu',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/news/')),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'context': 'news'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Custom.category')),
            ],
            options={
                'verbose_name': 'Notisia',
                'verbose_name_plural': 'Notisia',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/org/')),
                ('level', models.PositiveIntegerField(default=0, help_text='0 = puncak/Diretor Ezekutivu')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Website.orgmember')),
            ],
            options={
                'verbose_name': 'Membru Organigrama',
                'verbose_name_plural': 'Organigrama',
                'ordering': ['level', 'order'],
            },
        ),
    ]
