# Generated by Django 5.2.17 on 2026-09-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mensajen Kontaktu",
                "verbose_name_plural": "Mensajen Kontaktu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Mis. Sr. Estevanus Coli", max_length=150
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Kargu/jabatan atuál, mis. 'Actual Director MDI' ka 'Prezidente Koperativa FUNAMOR'",
                        max_length=200,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/founders/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Fundador",
                "verbose_name_plural": "Fundador (Founders)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/partners/"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("partner", "Parseiru"), ("donor", "Doador")],
                        default="partner",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Parseiru / Doador",
                "verbose_name_plural": "Parseiru / Doador",
                "ordering": ["type", "order"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kicker",
                    models.CharField(
                        help_text="Teks kecil di atas judul (bahasa Tetum, default)",
                        max_length=150,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="website/slides/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "kicker_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "title_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "text_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide Hero",
                "verbose_name_plural": "Slide Hero",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VisionMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vision_text", models.TextField(help_text="Teks default (Tetum)")),
                (
                    "mission_text",
                    models.TextField(
                        help_text="Teks default (Tetum), uza se mission_points mamuk"
                    ),
                ),
                (
                    "vision_text_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "mission_text_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "mission_points",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Lista misaun per lian: {"tet": ["...", "..."], "id": [...], "pt": [...], "en": [...]}',
                    ),
                ),
            ],
            options={
                "verbose_name": "Vizaun & Misaun",
                "verbose_name_plural": "Vizaun & Misaun",
            },
        ),
        migrations.CreateModel(
            name="WhoWeAre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_title", models.CharField(default="Profile", max_length=150)),
                ("profile_text", models.TextField(help_text="Teks default (Tetum)")),
                ("who_we_are_text", models.TextField(help_text="Teks default (Tetum)")),
                (
                    "profile_text_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "who_we_are_text_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                ("established_year", models.CharField(default="2005", max_length=10)),
                (
                    "based_in",
                    models.CharField(
                        default="Bebonuk, Comoro, Dili, Timor-Leste", max_length=150
                    ),
                ),
                (
                    "focus_area",
                    models.CharField(
                        default="Monitoring, Advocacy & Community Strengthening",
                        max_length=200,
                    ),
                ),
                (
                    "org_structure_title",
                    models.CharField(
                        blank=True, default="Estrutura Organizasionál", max_length=150
                    ),
                ),
                (
                    "org_structure_intro",
                    models.TextField(blank=True, help_text="Teks default (Tetum)"),
                ),
                (
                    "org_structure_intro_i18n",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "org_structure_items",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Lista bullet per lian: {"tet": ["...", ...], "id": [...], "pt": [...], "en": [...]}',
                    ),
                ),
                (
                    "org_structure_outro",
                    models.TextField(blank=True, help_text="Teks default (Tetum)"),
                ),
                (
                    "org_structure_outro_i18n",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "strategy_title",
                    models.CharField(
                        blank=True, default="Abordajen Estratéjiku", max_length=150
                    ),
                ),
                (
                    "strategy_text",
                    models.TextField(blank=True, help_text="Teks default (Tetum)"),
                ),
                ("strategy_text_i18n", models.JSONField(blank=True, default=dict)),
                (
                    "geo_focus_title",
                    models.CharField(
                        blank=True, default="Foku Jeográfiku", max_length=150
                    ),
                ),
                (
                    "geo_focus_intro",
                    models.TextField(blank=True, help_text="Teks default (Tetum)"),
                ),
                ("geo_focus_intro_i18n", models.JSONField(blank=True, default=dict)),
                (
                    "geo_focus_regions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Lista rejiaun per lian: {"tet": ["Dili", "Viqueque", ...], "id": [...], "pt": [...], "en": [...]}',
                    ),
                ),
                (
                    "geo_focus_outro",
                    models.TextField(blank=True, help_text="Teks default (Tetum)"),
                ),
                ("geo_focus_outro_i18n", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Ita Se (Who We Are)",
                "verbose_name_plural": "Ita Se (Who We Are)",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/activities/"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Urutan tampil manual di halaman 'What We Do' (semua aktivitas)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Dipakai untuk menentukan aktivitas terbaru di homepage",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom.municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividade",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("excerpt", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto sampul artigu (opsional, hasoru tampilan liu diak)",
                        null=True,
                        upload_to="website/articles/",
                    ),
                ),
                ("published_date", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"context": "article"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artigu",
                "verbose_name_plural": "Artigu",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("file", models.FileField(upload_to="website/documents/")),
                ("published_date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"context": "document"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="custom.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentu",
                "verbose_name_plural": "Dokumentu",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                ("excerpt", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="website/news/"),
                ),
                (
                    "location_detail",
                    models.CharField(
                        blank=True,
                        help_text="Detalhe lokasaun espesífiku, mis. 'Suku Guiço, Postu Same'",
                        max_length=200,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referénsia/fonte orijinál (opsional)",
                        max_length=200,
                    ),
                ),
                ("published_date", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"context": "news"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom.category",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        help_text="Munisípiu ne'ebe relasiona ho notísia ne'e",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom.municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notisia",
                "verbose_name_plural": "Notisia",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="website/news_gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="website.newspost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto Galeria Notísia",
                "verbose_name_plural": "Foto Galeria Notísia",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="website/org/"),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = puncak/Diretor Ezekutivu"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="website.orgmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membru Organigrama",
                "verbose_name_plural": "Organigrama",
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Label badak ba menu (Tetum, default)", max_length=150
                    ),
                ),
                (
                    "title_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Label menu: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "heading",
                    models.CharField(
                        help_text="Título kompletu (Tetum, default)", max_length=250
                    ),
                ),
                ("description", models.TextField(help_text="Teks default (Tetum)")),
                (
                    "heading_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "description_i18n",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Tradusaun: {"id":"..","pt":"..","en":".."}',
                    ),
                ),
                (
                    "indicators",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Indikadór Esperadu per lian: {"tet": ["...", ...], "id": [...], "pt": [...], "en": [...]}',
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-diagram-3",
                        help_text="Nome klase ikon Bootstrap Icons",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hela mamuk ba Pilar (top-level). Hili Pilar-inan ba sub-outcome (mis. 2.1, 2.2...).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="website.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programa",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="newspost",
            name="related_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Programa ne'ebe relasiona (mis. PNDS)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_news",
                to="website.program",
            ),
        ),
    ]
