# Generated by Django 6.1.1 on 2026-09-12 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 12, 12, 35, 30, 46222, tzinfo=datetime.timezone.utc), help_text='Dipakai untuk menentukan aktivitas terbaru di homepage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Urutan tampil manual di halaman 'What We Do' (semua aktivitas)"),
        ),
    ]
