# Generated by Django 6.1.1 on 2026-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_activity_created_at_alter_activity_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mis. Sr. Estevanus Coli', max_length=150)),
                ('position', models.CharField(help_text="Kargu/jabatan atuál, mis. 'Actual Director MDI' ka 'Prezidente Koperativa FUNAMOR'", max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/founders/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fundador',
                'verbose_name_plural': 'Fundador (Founders)',
                'ordering': ['order'],
            },
        ),
    ]
