# Generated by Django 6.1.1 on 2026-09-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Foto sampul artigu (opsional, hasoru tampilan liu diak)', null=True, upload_to='website/articles/'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/news_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Website.newspost')),
            ],
            options={
                'verbose_name': 'Foto Galeria Notísia',
                'verbose_name_plural': 'Foto Galeria Notísia',
                'ordering': ['order', 'id'],
            },
        ),
    ]
