# Generated by Django 6.1.1 on 2026-09-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0001_initial'),
        ('Website', '0004_article_cover_image_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmanmessage',
            name='message_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='location_detail',
            field=models.CharField(blank=True, help_text="Detalhe lokasaun espesífiku, mis. 'Suku Guiço, Postu Same'", max_length=200),
        ),
        migrations.AddField(
            model_name='newspost',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text="Munisípiu ne'ebe relasiona ho notísia ne'e", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Custom.municipality'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='related_program',
            field=models.ForeignKey(blank=True, help_text="Programa ne'ebe relasiona (mis. PNDS)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_news', to='Website.program'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Referénsia/fonte orijinál (opsional)', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='program',
            name='heading_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='slide',
            name='kicker_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='slide',
            name='text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='mission_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='vision_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='profile_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='who_we_are_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Tradusaun: {"id":"..","pt":"..","en":".."}'),
        ),
        migrations.AlterField(
            model_name='chairmanmessage',
            name='message',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='heading',
            field=models.CharField(help_text='Teks default (Tetum)', max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='kicker',
            field=models.CharField(help_text='Teks kecil di atas judul (bahasa Tetum, default)', max_length=150),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='mission_text',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
        migrations.AlterField(
            model_name='visionmission',
            name='vision_text',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='profile_text',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='who_we_are_text',
            field=models.TextField(help_text='Teks default (Tetum)'),
        ),
    ]
