# Generated by Django 5.2.17 on 2026-09-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0005_chairmanmessage_message_i18n_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChairmanMessage",
        ),
        migrations.AddField(
            model_name="program",
            name="indicators",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Indikadór Esperadu per lian: {"tet": ["...", ...], "id": [...], "pt": [...], "en": [...]}',
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Hela mamuk ba Pilar (top-level). Hili Pilar-inan ba sub-outcome (mis. 2.1, 2.2...).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="Website.program",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="title_i18n",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Label menu: {"id":"..","pt":"..","en":".."}',
            ),
        ),
        migrations.AddField(
            model_name="visionmission",
            name="mission_points",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Lista misaun per lian: {"tet": ["...", "..."], "id": [...], "pt": [...], "en": [...]}',
            ),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_intro",
            field=models.TextField(blank=True, help_text="Teks default (Tetum)"),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_intro_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_outro",
            field=models.TextField(blank=True, help_text="Teks default (Tetum)"),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_outro_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_regions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Lista rejiaun per lian: {"tet": ["Dili", "Viqueque", ...], "id": [...], "pt": [...], "en": [...]}',
            ),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="geo_focus_title",
            field=models.CharField(
                blank=True, default="Foku Jeográfiku", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_intro",
            field=models.TextField(blank=True, help_text="Teks default (Tetum)"),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_intro_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_items",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Lista bullet per lian: {"tet": ["...", ...], "id": [...], "pt": [...], "en": [...]}',
            ),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_outro",
            field=models.TextField(blank=True, help_text="Teks default (Tetum)"),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_outro_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="org_structure_title",
            field=models.CharField(
                blank=True, default="Estrutura Organizasionál", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="strategy_text",
            field=models.TextField(blank=True, help_text="Teks default (Tetum)"),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="strategy_text_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whoweare",
            name="strategy_title",
            field=models.CharField(
                blank=True, default="Abordajen Estratéjiku", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="heading",
            field=models.CharField(
                help_text="Título kompletu (Tetum, default)", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="title",
            field=models.CharField(
                help_text="Label badak ba menu (Tetum, default)", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="visionmission",
            name="mission_text",
            field=models.TextField(
                help_text="Teks default (Tetum), uza se mission_points mamuk"
            ),
        ),
        migrations.AlterField(
            model_name="whoweare",
            name="established_year",
            field=models.CharField(default="2005", max_length=10),
        ),
    ]
