# Generated by Django 5.2.17 on 2026-09-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Mata Dalan Institute", max_length=150),
                ),
                ("short_name", models.CharField(default="MDI", max_length=20)),
                (
                    "tagline",
                    models.CharField(
                        default="Monitoring . Advocacy . Community Strengthening",
                        max_length=200,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="config/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="config/"),
                ),
                ("email", models.EmailField(default="info@mditl.org", max_length=254)),
                ("phone", models.CharField(default="+670 7845 9090", max_length=30)),
                (
                    "address",
                    models.CharField(
                        default="Bebonuk, Comoro, Dili, Timor-Leste", max_length=255
                    ),
                ),
                (
                    "activity_location_name",
                    models.CharField(
                        default="Tasi Tolu, Dili, Timor-Leste", max_length=255
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=12, default=-8.563037754273, max_digits=15
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=12, default=125.501539777895, max_digits=15
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        default="https://www.facebook.com/matadalaninstitute/",
                    ),
                ),
                (
                    "blog_url",
                    models.URLField(
                        blank=True, default="https://matadalaninstitute.blogspot.com/"
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="Institute For Monitoring, Advocacy And Community Strengthening - organizasaun naun-governamentál (ONG) ne'ebe harii iha Timor-Leste dezde tinan 2005."
                    ),
                ),
                (
                    "footer_credit",
                    models.CharField(
                        default="Site ne'e dezenvolve ho Bootstrap 5 & Django.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfigurasaun Situs",
                "verbose_name_plural": "Konfigurasaun Situs",
            },
        ),
    ]
