# Generated by Django 5.2.17 on 2026-10-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="flagcounter_id",
            field=models.CharField(
                blank=True,
                help_text='ID kontador husi flagcounter.com — halo konta gratis iha https://flagcounter.com/ (klik "Get your free counter!"), kopia deit ID ne\'ebe mosu iha URL imajen (mis. husi https://s11.flagcounter.com/count2/<b>abcd</b>/... ID = "abcd"). Se mamuk, widget visitante-per-nasaun la hatudu iha site.',
                max_length=20,
                verbose_name="FlagCounter ID",
            ),
        ),
    ]
