# Generated by Django 5.2.17 on 2026-10-01 06:29

from django.db import migrations, models


def set_default_flagcounter_id(apps, schema_editor):
    """Backfill flagcounter_id iha rejistu SiteConfig ne'ebe ona eziste (kriadu
    antes field ida-ne'e iha default) — atu ID real MDI nian aparese la presiza
    utilizador edita Admin manualmente depois deploy/migrate foun."""
    SiteConfig = apps.get_model("config", "SiteConfig")
    SiteConfig.objects.filter(flagcounter_id="").update(flagcounter_id="GRdh")


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_siteconfig_flagcounter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="flagcounter_id",
            field=models.CharField(
                blank=True,
                default="GRdh",
                help_text='ID kontador husi flagcounter.com — halo konta gratis iha https://flagcounter.com/ (klik "Get your free counter!"), kopia deit ID ne\'ebe mosu iha URL imajen (mis. husi https://s11.flagcounter.com/count2/<b>abcd</b>/... ID = "abcd"). Se mamuk, widget visitante-per-nasaun la hatudu iha site.',
                max_length=20,
                verbose_name="FlagCounter ID",
            ),
        ),
        migrations.RunPython(set_default_flagcounter_id, migrations.RunPython.noop),
    ]
