# Generated by Django 6.1.1 on 2026-09-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('context', models.CharField(choices=[('news', 'Notisia'), ('article', 'Artigu'), ('document', 'Dokumentu'), ('activity', 'Atividade')], default='news', max_length=20)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategoria',
                'ordering': ['context', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Munisípiu',
                'verbose_name_plural': 'Munisípiu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Tinan',
                'verbose_name_plural': 'Tinan',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Custom.municipality')),
            ],
            options={
                'verbose_name': 'Postu Administrativu',
                'verbose_name_plural': 'Postu Administrativu',
                'ordering': ['municipality__name', 'name'],
                'unique_together': {('municipality', 'name')},
            },
        ),
    ]
